// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class PedestrianPosition {
	private int flooID;
	private float time;
	private float x;
	private float y;
    private float z;
	public PedestrianPosition (int id, float time, float x, float y, float z) {
		this.flooID = id;
		this.time = time;
		this.x = x;
		this.y = y;
        this.z = z;
	}

	public int getFloorID() {return this.flooID;}
	public float getTime() {return this.time;}
	public float getX() {return this.x;}
	public float getY() {return this.y;}
    public float getZ() {return this.z;}

    public bool equals(PedestrianPosition pos) {
        return x == pos.getX() && y == pos.getY() && z == pos.getZ();
	}
}
