// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class PedestrianPosition {
	private int id;
	private decimal time;
	private float x;
	private float y;
	public PedestrianPosition (int id, decimal time, float x, float y) {
		this.id = id;
		this.time = time;
		this.x = x;
		this.y = y;
	}

	public int getID() {return this.id;}
	public decimal getTime() {return this.time;}
	public float getX() {return this.x;}
	public float getY() {return this.y;}

	public bool equals(PedestrianPosition pos) {
		return x == pos.getX () && y == pos.getY ();
	}
}
